apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: n8n-worker
  name: n8n-worker
  namespace: n8n
spec:
  replicas: 2
  selector:
    matchLabels:
      service: n8n-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: n8n-worker
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: n8n-claim0
              mountPath: /data
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n worker
          env:
            # Database Configuration
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres-service.n8n.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            # Redis Queue Configuration
            - name: QUEUE_BULL_REDIS_HOST
              value: redis-service.n8n.svc.cluster.local
            - name: QUEUE_BULL_REDIS_PORT
              value: "6379"
            # Queue Mode Configuration
            - name: EXECUTIONS_MODE
              value: queue
            # Worker-specific Configuration
            - name: N8N_LOG_LEVEL
              value: info
            - name: QUEUE_HEALTH_CHECK_PORT
              value: "5679"
            # Security and Performance
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_METRICS
              value: "false"
            - name: N8N_DIAGNOSTICS_ENABLED
              value: "false"
            - name: N8N_HIRING_BANNER_ENABLED
              value: "false"
            - name: N8N_UNVERIFIED_PACKAGES_ENABLED
              value: "false"
            - name: NODES_EXCLUDE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: NODES_EXCLUDE
            - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
              value: "true"
            - name: GENERIC_TIMEZONE
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: GENERIC_TIMEZONE
            # Process Configuration
            - name: N8N_WORKERS_ENABLED
              value: "true"
            # Encryption Key (REQUIRED - must match main instance)
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_ENCRYPTION_KEY
          image: n8nio/n8n
          name: n8n-worker
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-claim0
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: postgres-secret
          secret:
            secretName: postgres-secret