apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: n8n-secret
type: Opaque
stringData:
  # Encryption key for n8n data encryption (REQUIRED - must be 32 characters)
  # Generate with: openssl rand -base64 32
  N8N_ENCRYPTION_KEY: "changeme-32-character-encryption-key"
  
  # Webhook URL for external access (optional - update with your domain)
  N8N_WEBHOOK_URL: "https://your-domain.com/"
  
  # Editor base URL (optional - update with your domain)  
  N8N_EDITOR_BASE_URL: "https://your-domain.com/"
  
  # JWT secret for authentication (optional but recommended)
  # Generate with: openssl rand -base64 64
  N8N_JWT_SECRET: "changeme-jwt-secret-key-for-authentication"
  
  # Basic auth credentials for n8n (optional)
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "changeme-admin-password"
  
  # License activation key (optional - for enterprise features)
  # N8N_LICENSE_ACTIVATION_KEY: "your-license-key-here"
  
  # Nodes to exclude (empty array means no nodes are excluded)
  NODES_EXCLUDE: "[]"
  
  # Default timezone for n8n instance
  GENERIC_TIMEZONE: "America/Vancouver"
  
  # SMTP Email Configuration
  N8N_EMAIL_MODE: "smtp"
  N8N_SMTP_HOST: "smtp.gmail.com"
  N8N_SMTP_PORT: "587"
  N8N_SMTP_USER: "your-email@gmail.com"
  N8N_SMTP_PASS: "your-app-password"
  N8N_SMTP_SENDER: "your-email@gmail.com"
  N8N_SMTP_SSL: "false"
  N8N_SMTP_OAUTH_SERVICE_CLIENT: ""
  N8N_SMTP_OAUTH_PRIVATE_KEY: ""